name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          #- "windows-latest"
          #- "macOS-latest"
        php:
          - "7.2"
          - "7.3"
          - "7.4"
    name: PHP ${{ matrix.php }} checks on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install environment
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring
          coverage: pcov
          tools: prestissimo

      - name: Cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Linting
        run: composer run test:lint

      - name: Static code analysis
        run: composer run test:analysis

      - name: Tests and coverage
        run: composer run test:coverage

      - name: Coverage report
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success() && matrix.php == '7.4'
        run: composer run test:coverage:report

      - name: Sonar Scanner
        uses: sonarsource/sonarcloud-github-action@master
        if: success() && matrix.php == '7.4'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
